// ──────────────────────────────────────────────────────────────────────────────
// Scenario: Secure New — fully managed enclave, community, workload, and server.
//
// Deploy with:
//   az deployment sub create \
//     --location <region> \
//     --parameters ave-templates/workloads/postgresql/examples/postgresql-secure-new.bicepparam
//
// Replace every placeholder value (Community name, CIDR, and object IDs) before deploying.
// Do not edit avePostgreSql.bicep. Customers author only this .bicepparam file.
// ──────────────────────────────────────────────────────────────────────────────

using '../avePostgreSql.bicep'

// Deployment location is passed through the --location argument on the CLI; no
// override is required here unless you want to force a specific region.
param deploymentContext = {
  tags: {
    environment: 'production'
    workload: 'postgresql'
  }
}

// Object ID of the identity running the deployment. Used to seed the Mission
// maintenance-principal set for the managed enclave.
param deploymentPrincipal = {
  objectId: '11111111-1111-1111-1111-111111111111' // ← replace with real object ID
  principalType: 'User'
}

// ─── Community ────────────────────────────────────────────────────────────────
// Managed: a new Mission community is created in the named resource group.
// Switch to mode: 'existing' and supply resourceId to reuse an existing one.
param community = {
  mode: 'managed'
  name: 'contoso-community'
  resourceGroupName: 'rg-contoso-community'
}

// ─── Enclave ──────────────────────────────────────────────────────────────────
// resourceId is omitted, so a new Mission virtual enclave is created. All four
// approval settings must be declared explicitly when creating a new enclave;
// they represent desired state. NotRequired is the recommended secure-new
// starting point. Switch individual actions to Required (with
// mandatoryApprovers and minimumApproversRequired) to enforce approval-gate
// workflows once the environment is established. Name, resource group, and /24
// subnet requests use Community-derived defaults.
param enclave = {
  addressSpaceCidr: '10.250.0.0/16' // ← choose a non-overlapping CIDR
  approvalSettings: {
    connectionCreation: {
      approvalPolicy: 'NotRequired'
    }
    connectionUpdate: {
      approvalPolicy: 'NotRequired'
    }
    enclaveEndpointUpdate: {
      approvalPolicy: 'NotRequired'
    }
    enclaveMaintenanceMode: {
      approvalPolicy: 'NotRequired'
    }
  }
}

// ─── Workload ─────────────────────────────────────────────────────────────────
// Omitted: defaults to managed with Community-derived workload and RG names.

// ─── Foundation (server identity, Key Vault, key, private DNS) ───────────────
// Omitted: all five foundation selections default to managed mode.

// ─── Network finalization ──────────────────────────────────────────────────────
// Omitted networkFinalization defaults to Managed. communityConnectivity below
// adds the outbound allow rule required for private-network Microsoft Entra
// authentication, per:
// https://learn.microsoft.com/en-us/azure/postgresql/security/security-entra-configure
// ("Add an outbound NSG rule that allows traffic to the AzureActiveDirectory
// service tag"). This profile never writes NSGs directly; Mission's
// community-endpoint/enclave-connection contract expresses the equivalent
// allow rule so it is regenerated by redeployment. Mission denies everything
// else by default, so this entry is additive.
param communityConnectivity = [
  {
    endpoint: {
      mode: 'managed'
      ruleCollection: [
        {
          endpointRuleName: 'aad-entra-outbound'
          destinationType: 'ServiceTag'
          destination: 'AzureActiveDirectory'
          protocols: [
            'TCP'
          ]
          ports: '443'
        }
      ]
    }
    sourceSubnets: [
      'DelegatedPostgreSql'
    ]
  }
]

// ─── PostgreSQL Flexible Server ────────────────────────────────────────────────
// Replace administrators[0] with your DBA group or user Entra object ID,
// principalName (UPN or display name), and tenantId.
param server = {
  mode: 'managed'
  administrators: [
    {
      objectId: '22222222-2222-2222-2222-222222222222' // ← replace
      principalName: 'dba-group@contoso.example'      // ← replace
      principalType: 'Group'
      tenantId: '33333333-3333-3333-3333-333333333333' // ← replace with tenant().tenantId or literal GUID
    }
  ]
}
